### ISSUE TITLE
Confusion about slave's epoch field in the example of CLUSTER NODES doc

### ISSUE THREAD

**Issue by chanjarster** [redis/redis-doc#1138]
[CLUSTER NODES doc says](https://redis.io/commands/cluster-nodes#notes-on-published-config-epochs):

```
Replicas broadcast their master's config epochs ...
```

But the example given in the [doc](https://redis.io/commands/cluster-nodes#serialization-format) doesn't obey that:

* slave 127.0.0.1:30004 epoch is 4, while it's master's epoch is 1
* slave 127.0.0.1:30005 epoch is 5, while it's master's epoch is 2
* slave 127.0.0.1:30006 epoch is 6, while it's masters' epoch is 3

```txt
07c37dfeb235213a872192d90877d0cd55635b91 127.0.0.1:30004 slave e7d1eecce10fd6bb5eb35b9f99a514335d9ba9ca 0 1426238317239 4 connected
67ed2db8d677e59ec4a4cefb06858cf2a1a89fa1 127.0.0.1:30002 master - 0 1426238316232 2 connected 5461-10922
292f8b365bb7edb5e285caf0b7e6ddc7265d2f4f 127.0.0.1:30003 master - 0 1426238318243 3 connected 10923-16383
6ec23923021cf3ffec47632106199cb7f496ce01 127.0.0.1:30005 slave 67ed2db8d677e59ec4a4cefb06858cf2a1a89fa1 0 1426238316232 5 connected
824fe116063bc5fcf9f4ffd895bc17aee7731ac3 127.0.0.1:30006 slave 292f8b365bb7edb5e285caf0b7e6ddc7265d2f4f 0 1426238317741 6 connected
e7d1eecce10fd6bb5eb35b9f99a514335d9ba9ca 127.0.0.1:30001 myself,master - 0 0 1 connected 0-5460
```

**Comment by mich-elle-luna** [comment]
I think this doc note explains it: Notes on published config epochs https://redis.io/commands/cluster-nodes/

Replicas broadcast their primary's config epochs (in order to get an UPDATE message if they are found to be stale), so the real config epoch of the replica (which is meaningless more or less, since they don't serve hash slots) can be only obtained checking the node flagged as myself, which is the entry of the node we are asking to generate CLUSTER NODES output. The other replicas epochs reflect what they publish in heartbeat packets, which is, the configuration epoch of the primaries they are currently replicating.
