### ISSUE TITLE
[BUG]The example do not show correct result in ZMPOP and LMPOP command doc page

### ISSUE THREAD

**Issue by hwware** [redis/redis-doc#1684]
**Describe the bug**

In the command document page for new ZMPOP and LMPOP command,
https://redis.io/commands/lmpop and https://redis.io/commands/zmpop
The example always display: ERR Don't know what to do for "zmpop" and ERR Don't know what to do for "lmpop"

**To reproduce**

Steps to reproduce the behavior and/or a minimal code sample.

**Expected behavior**

A description of what you expected to happen.

**Additional information**

Any additional information that is relevant to the problem.

**Comment by oranagra** [comment]
@hwware we have another repo for redis-doc, so this belongs there (moved)
but anyway, IIUC the problem is that these examples run on a real redis server (you can edit that text box and type `INFO server` press enter and it'll reply).
and that redis is still using redis 6.2, so new 7.0 commands don't work.

**Comment by hwware** [comment]
> @hwware we have another repo for redis-doc, so this belongs there (moved) but anyway, IIUC the problem is that these examples run on a real redis server (you can edit that text box and type `INFO server` press enter and it'll reply). and that redis is still using redis 6.2, so new 7.0 commands don't work.

Thanks Oran, understand, i will close this issue.
