### ISSUE TITLE
SINTERCARD doc error

### ISSUE THREAD

**Issue by ilovcoding** [redis/redis-doc#1952]
![image](https://user-images.githubusercontent.com/34740295/169491281-42ae62fb-9366-4b3d-b207-836ab8ce9a0e.png)
## Run in my linux server
![image](https://user-images.githubusercontent.com/34740295/169491878-7e2366f5-fe70-455d-a8c2-480e23f2dafb.png)

**Comment by itamarhaber** [comment]
Hi @ilovcoding - thanks for reporting this issue.

I believe this is a known issue that was fixed by https://github.com/redis/redis-clinterwebz/pull/7. After deploying the fix I can verify that this is resolved:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/6059516/173189904-993eb59c-cad0-45bc-8e43-bff7d0c569f9.png">
