### ISSUE TITLE
GEOSEARCH syntax should be lowercase for units

### ISSUE THREAD

**Issue by masyukun** [redis/redis-doc#2092]
The [Redis.io](http://redis.io/)’s command documentation seems to indicate that Geospatial index functions like [GEOSEARCH](https://redis.io/commands/geosearch/) and [GEORADIUS](https://redis.io/commands/georadius/) accept only uppercase units (M, KM, FT, MI) but in reality, the server will only accept lowercase versions (m, km, ft, mi). We should update the usage syntax to clarify this.

**Comment by itamarhaber** [comment]
Hi @masyukun and thanks for reporting this.

Generally, Redis is case insensitive regarding command names and keywords. Also, the convention in Redis' syntax, is to use capital-case for keywords and lower-case for user input.

In versions older than Redis 7 the units were indeed lowercase-only, but that has been remedied so now both forms are acceptable. Therefore, I believe the correct resolution for this issue is via https://github.com/redis/redis/pull/11162.

@guybe7 WDUT?

**Comment by guybe7** [comment]
@masyukun perhaps it isn't mentioned anywhere but redis is completely case insensitive (always has been)

@itamarhaber yes, i guess it's worth mentioning that in the command history, but i did post a comment: https://github.com/redis/redis/pull/11162#issuecomment-1221554313

**Comment by nermiller** [comment]
@itamarhaber, ok to close?

**Comment by itamarhaber** [comment]
Yes, we can close this imo (note that the fix will only be visible once we release a new version of Redis).
