### ISSUE TITLE
RESP protocol spec

### ISSUE THREAD

**Issue by jobol** [redis/redis-doc#2203]
Suggestion of tiny improvement: Explain encoding:
- tell that character must not be wide (neither 16bits nor 32bits)
- tell that multibyte encoding are preserved if it does not collide with CR LF

**Comment by PerMildner** [comment]
As an outsider, my interpretation is that the RESP-protocol is a binary stream-of-bytes protocol. In some contexts the bytes are interpreted as ASCII, and in some contexts (e.g. length of Bulk String) a sequence of bytes is interpreted as a (ASCII-) textual character sequence denoting an integer. I see nothing of this mentioned in the [RESP protocol spec](https://redis.io/docs/reference/protocol-spec/).

For instance, the Bulk string format is described as [A "$" byte followed by the number of bytes composing the string](https://redis.io/docs/reference/protocol-spec/#resp-bulk-strings) but, and this is only apparent from the examples, this is false. Instead the a Bulk string actually is more like A` "$" byte followed by bytes making up the base-10 textual representation, in most significant digit first order, of the number of bytes composing the string` (yes, this becomes verbose but precise and non-verbose specification of binary protocol is a well studied subject, so there should be many good notations to choose from).

I also see nothing about the text encoding for mapping text to the bytes in the protocol except the implicit ASCII/Latin 1/UTF-8 (which are all equivalent when) used for command names and integer digits and minus sign.

As an outsider, my guess would be that string data is actually byte data, e.g. a Simple string is a sequence of bytes (which cannot include the byte values `10` or `13` (but can include zero?).

If it _is_ byte data, then it is not characters, and certainly not "wide characters" and preserving multibyte encoding becomes strictly a client level issue when it decides how to encode its text data into the RESP byte data.

The above "everything is bytes" interpretation works fine when sending data from the client to Redis that Redis itself does not interpret.

However, the  "everything is bytes" interpretation is insufficient when Redis sends data (like error messages) back to the client and the client is supposed to interpret the data as text. In this case Redis or RESP should specify how a byte sequence is to be decodes as text, otherwise the error messages are just uninterpretable gibberish. Perhaps the number of such messages are few and simple and always can be treated as ASCII, I do not know.

As I mentioned, I am an outsider, so I cannot build on prior knowledge about how Redis actually works. I just read the RESP specification literally, and it is not sufficiently precise, e.g. for confidently building a RESP client.

**Comment by itamarhaber** [comment]
Hello @jobol & @PerMildner !

Both POV's are extremely important, thanks for bringing them into focus, and my apologies for being so late to reply.

I've tried addressing and improving upon these aspects in a forthcoming update to the protocol docs - #1920 - I'd appreciate your valuable feedback if you can spare the time to review :)
