### ISSUE TITLE
Redis replication

### ISSUE THREAD

**Issue by RalphAraujo** [redis/redis-doc#2235]
After 4 hours processing , I have this error : 
ReplyError: READONLY You can't write against a read only replica.
     at parseError (/app/node_modules/redis-parser/lib/parser.js:179:12)
     at parseType (/app/node_modules/redis-parser/lib/parser.js:302:14) {
   command: {
     name: 'set',
     args: [ 'BTCUSDT_LAST_DAY', '2022-12-05T16:32:22-03:00' ]
   }
 }
 
AND 

Redis.
 "REPLICAOF"
2) "185.246.90.203 8886"

I need help to understand and fix this problem 

tks

**Comment by itamarhaber** [comment]
Hi @RalphAraujo 

The error is because your application is trying to perform a write operation (the [`SET` command](https://redis.io/commands/set) against a read-only replica.

It is impossible to know what causes this without the details of the Redis client you're using, your connection's configuration, and Redis' deployment state. That said, this is likely caused by misconfiguration/misuse :)
