### ISSUE TITLE
Docs - CLIENT LIST change missing in history

### ISSUE THREAD

**Issue by jimsnab** [redis/redis-doc#2287]
Minor: `resp` version was added in redis 7, but is not listed in docs page under History.

**Comment by enjoy-binbin** [comment]
https://github.com/redis/redis/blob/unstable/src/commands/client-list.json#L10
I see we do list field changes in history.
but not only resp is missing
some i know：
- multi-mem 7.0.0
- resp 7.0.0
- ssub 7.0.3
- redir 6.2.0
- ....

@oranagra Do you think if we need to add it? there are a lot field changes are missing

**Comment by oranagra** [comment]
right, i do remember this PR https://github.com/redis/redis/pull/10398/files in which we removed some history comments that are not about the interface (arguments and outputs), but these are indeed about the output.
on the other hand, CLIENT LIST is similar to INFO, in the sense that it's just a dictionary of a of fields, not sure we should document each one.

i guess at least `resp` makes sense to be documented, and since there are some fields already there, we can make the effort to document the others.
feel free to make a PR.

**Comment by oranagra** [comment]
merged.
