### ISSUE TITLE
Misleading time complexity for georadius

### ISSUE THREAD

**Issue by halaei** [redis/redis-doc#999]
I thing this statement is a little bit misleading:

> Time complexity: O(N+log(M)) where N is the number of elements inside the bounding box of the circular area delimited by center and radius and M is the number of items inside the index.

The problem is that "bounding box" is not clearly defined. I think in general the term refers to minimal bounding box, meaning the smallest orthogonal rectangle that covers the queried circle. I that case, it is impossible to support O(N+log(M)) time complexity in the worst case scenario. I am not sure about the exact time complexity, but I guess it is not going to be any better than O(N + sqrt(M)).

**Comment by antirez** [comment]
Hello @halaei, yes there must be an error there, because AFAIK to query an N-dimensional index has a worst case of sqrt(M). However to be honest normally in the Redis documentation we don't advertise the worst case but the average one... Otherwise we should consider all the hash table lookups O(N) for instance. There is more, the worst case sqrt(M) in 2-dim indexing is hit, AFAIK, when there is a very uneven query in the two dimensions (intuitively in that case you have to query many small squares for all the length of the two dimensions, making it sqrt M). However we query even areas because we have a circular radius and latitude and longitude follow a similar step (if not for a constant 2x difference factor), so AFAIK the complexity may really be N+log(M) in that particular case.

**Comment by antirez** [comment]
Well actually reading the implementation and the operations we do in the skiplist, this really seems to be the case. We do a work proportional to the N*K items, where K is a constant factor needed in order to filter away the elements outside the circle area, plus the seeking performed by the skiplist which is O(Log M).

**Comment by halaei** [comment]
I think in practice the time complexity is indeed good enough.
I also agree with you about (N*K) part and the definition of K, which is a constant. My problem is with the definition of N and bounding box. Are all the N*K items that the implementation scans within a minimum orthogonal bounding box or bonding box here means something else?

My understanding of time complexity is a little bit gone by the pass of time. However, about hash table, I remember at least it is possible to implement a hash table with O(1) worst case time complexity "with high-probability", according to the following definition I found in wikipedia. Not sure if all popular implementations of hash table achieve it though:

> In mathematics, an event that occurs with high probability (often shortened to w.h.p. or WHP) is one whose probability depends on a certain number n and goes to 1 as n goes to infinity, i.e. it can be made as close as desired to 1 by making n big enough.

**Comment by mich-elle-luna** [comment]
I believe the statement in question no longer exists in the docs. Closing.
